### ISSUE TITLE
Day 18?

### ISSUE THREAD

**Issue by Kingfrankbob** [bradwilson/advent-2022#1]
Hello, I have been using your code as a reference, and I plug  in my input for  part 2, and it does not work? I get 2545, and the website claims it is not the right answer, do you mind plugging it in temporarily? If not I can close the issue...

[Input.txt](https://github.com/bradwilson/advent-2022/files/10254843/Input.txt)

EDIT: When I ran it on my machine I got 2545, and running a  different I got 2564. 

Again, I apologize if it is just my machine, do not want to waste time!

**Comment by Kingfrankbob** [comment]
It turned out to be the way I was running it plus a slight adjustment to the code!

**Comment by bradwilson** [comment]
It's sometimes common that I luck into a solution that works for me but missed some edge case that fails for someone else's data set.

Or, in the case of Day 22, I hand crafted code that's pretty much guaranteed to only work if your map layout is exactly the same as mine. 😂
